---

- set_fact:
    mxisd_url_endpoint_public: "https://{{ matrix_server_fqn_matrix }}/_matrix/identity/api/v1"

- name: Check mxisd Identity Service
  uri:
    url: "{{ mxisd_url_endpoint_public }}"
    follow_redirects: none
    validate_certs: "{{ matrix_mxisd_self_check_validate_certificates }}"
  register: result_mxisd
  ignore_errors: true

- name: Fail if mxisd Identity Service not working
  fail:
    msg: "Failed checking mxisd is up at `{{ matrix_server_fqn_matrix }}` (checked endpoint: `{{ mxisd_url_endpoint_public }}`). Is mxisd running? Is port 443 open in your firewall? Full error: {{ result_mxisd }}"
  when: "result_mxisd.failed or 'json' not in result_mxisd"

- name: Report working mxisd Identity Service
  debug:
    msg: "mxisd at `{{ matrix_server_fqn_matrix }}` is working (checked endpoint: `{{ mxisd_url_endpoint_public }}`)"
